version: "3.9"

services:
  spark:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: spark-lakehouse:dev
    container_name: spark-lakehouse
    tty: true
    stdin_open: true
    env_file:
      - ../.env  #variables AWS et autres secrets 
    volumes:
      - ../src:/opt/lakehouse/lakehouse
      - ../config:/opt/lakehouse/config:ro
      - lakehouse_data:/opt/lakehouse/data #volume pour les fichiers lourds
    depends_on:
      - data_init
    
    ports:
      - "4040:4040"   # spark UI
      - "8888:8888"   # jupyter
      - "18080:18080" #spark History Server

    command: tail -f /dev/null  # Garde le conteneur actif pour exec

  data_init:
    image: alpine
    volumes:
      - ../data:/tmp/data:ro
      - lakehouse_data:/opt/lakehouse/data
    entrypoint: ["sh", "-c", "cp -rn /tmp/data/* /opt/lakehouse/data/ || true"]
    restart: "no"

volumes:
  lakehouse_data:
    driver: local
